import type { NextPage } from 'next';
import Head from 'next/head';
import { Suspense } from 'react';
import { CompaniesLayout } from '../src/components';

const Home: NextPage = () => {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Companies list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Suspense fallback={'loading'}>
        <CompaniesLayout />
      </Suspense>
    </div>
  );
};

export default Home;
